### ISSUE TITLE
Suporte do storm para python 3.7

### ISSUE THREAD

**Issue by samosaara** [stoq/stoq#16]
O fork de python 3 da biblioteca storm do projeto, não está funcionando mais com o python 3.7, não sei exatamente o problema ou a mudança mas o erro é sempre esse:
```
09:19:04 stoq.gui.shell.bootstrap Traceback (most recent call last):
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoq/gui/shell/shell.py", line 529, in _on_app__activate
09:19:04 stoq.gui.shell.bootstrap     self._dbconn.connect()
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoq/gui/shell/shell.py", line 71, in connect
09:19:04 stoq.gui.shell.bootstrap     self._post_connect()
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoq/gui/shell/shell.py", line 155, in _post_connect
09:19:04 stoq.gui.shell.bootstrap     self._check_schema_migration()
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoq/gui/shell/shell.py", line 163, in _check_schema_migration
09:19:04 stoq.gui.shell.bootstrap     if needs_schema_update():
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/database/migration.py", line 553, in needs_schema_update
09:19:04 stoq.gui.shell.bootstrap     update = not (migration.check_uptodate() and migration.check_plugins())
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/database/migration.py", line 471, in check_plugins
09:19:04 stoq.gui.shell.bootstrap     for plugin in self._get_plugins():
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/database/migration.py", line 457, in _get_plugins
09:19:04 stoq.gui.shell.bootstrap     for plugin_name in manager.installed_plugins_names:
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/lib/pluginmanager.py", line 144, in installed_plugins_names
09:19:04 stoq.gui.shell.bootstrap     return self.get_installed_plugins_names()
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/lib/pluginmanager.py", line 120, in get_installed_plugins_names
09:19:04 stoq.gui.shell.bootstrap     return InstalledPlugin.get_plugin_names(store or get_default_store())
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/domain/plugin.py", line 53, in get_plugin_names
09:19:04 stoq.gui.shell.bootstrap     Ne(cls.plugin_version, None))]
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/domain/plugin.py", line 52, in <listcomp>
09:19:04 stoq.gui.shell.bootstrap     return [p.plugin_name for p in store.find(cls,
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/storm/store.py", line 997, in __iter__
09:19:04 stoq.gui.shell.bootstrap     result = self._store._connection.execute(self._get_select())
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/storm/databases/postgres.py", line 308, in execute
09:19:04 stoq.gui.shell.bootstrap     return Connection.execute(self, statement, params, noresult)
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/storm/database.py", line 243, in execute
09:19:04 stoq.gui.shell.bootstrap     statement = self.compile(statement, state)
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/storm/expr.py", line 678, in compile_select
09:19:04 stoq.gui.shell.bootstrap     tokens.append(compile(select.where, state, raw=True))
09:19:04 stoq.gui.shell.bootstrap   File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/storm/expr.py", line 1167, in compile_compound_oper
09:19:04 stoq.gui.shell.bootstrap     return compile(expr.exprs, state, join=expr.oper, raw=True)
09:19:04 stoq.gui.shell.bootstrap TypeError: argument 3 must be bytes, not str
Traceback (most recent call last):
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoq/gui/shell/shell.py", line 529, in _on_app__activate
    self._dbconn.connect()
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoq/gui/shell/shell.py", line 71, in connect
    self._post_connect()
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoq/gui/shell/shell.py", line 155, in _post_connect
    self._check_schema_migration()
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoq/gui/shell/shell.py", line 163, in _check_schema_migration
    if needs_schema_update():
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/database/migration.py", line 553, in needs_schema_update
    update = not (migration.check_uptodate() and migration.check_plugins())
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/database/migration.py", line 471, in check_plugins
    for plugin in self._get_plugins():
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/database/migration.py", line 457, in _get_plugins
    for plugin_name in manager.installed_plugins_names:
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/lib/pluginmanager.py", line 144, in installed_plugins_names
    return self.get_installed_plugins_names()
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/lib/pluginmanager.py", line 120, in get_installed_plugins_names
    return InstalledPlugin.get_plugin_names(store or get_default_store())
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/domain/plugin.py", line 53, in get_plugin_names
    Ne(cls.plugin_version, None))]
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/stoq-3.1.0-py3.7.egg/stoqlib/domain/plugin.py", line 52, in <listcomp>
    return [p.plugin_name for p in store.find(cls,
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/storm/store.py", line 997, in __iter__
    result = self._store._connection.execute(self._get_select())
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/storm/databases/postgres.py", line 308, in execute
    return Connection.execute(self, statement, params, noresult)
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/storm/database.py", line 243, in execute
    statement = self.compile(statement, state)
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/storm/expr.py", line 678, in compile_select
    tokens.append(compile(select.where, state, raw=True))
  File "/home/samuel/Projetos/stoq/venv3/lib/python3.7/site-packages/storm/expr.py", line 1167, in compile_compound_oper
    return compile(expr.exprs, state, join=expr.oper, raw=True)
TypeError: argument 3 must be bytes, not str
```
Não sei qual o processo de consertar isso, mas eu recomendaria esse outro fork que já suporta python 3.7, nem que seja pra adaptar, caso migração não seja possível: 
https://github.com/runfalk/storm-legacy

**Comment by DiegoSantanadss** [comment]
Qual seria o processo para realizar a instalação desse fork? Sou iniciante em python.

**Comment by DiegoSantanadss** [comment]
Não estou conseguindo rodar o projeto Stoq devido a não instalação do storm, diz que não é suportado para python 3.6.
