### ISSUE TITLE
Manuais de Instalação desatualizados

### ISSUE THREAD

**Issue by renato04** [stoq/stoq#18]
Olá tudo bem?
Estou tentando instalar o sistema seguindo o tutorial: [Começando](https://wiki.stoq.com.br/index.php/Come%C3%A7ando)
E ao tentar instalar os `requirements` da erro.

```
renato@renato-Virtual-Machine:~/repos/stoq$ pip3 install -r requirements.txt 
Collecting Mako>=0.2.5 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/f9/93/63f78c552e4397549499169198698de23b559b52e57f27d967690811d16d/Mako-1.0.10.tar.gz
Collecting Pillow>=1.1.5 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/d2/c2/f84b1e57416755e967236468dcfb0fad7fd911f707185efc4ba8834a1a94/Pillow-6.0.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting kiwi-gtk>=3.0 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/af/1a/a9a667a45901792605b09b6d72d4bc5d5bf3a81385064bf7a92f629f22ce/kiwi_gtk-3.0.3-py3-none-any.whl
Collecting stoqdrivers>=1.6 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/fb/f2/5d0c0c7daec21fa027d4585795e421efb728073bc594eb52d7035c779b19/stoqdrivers-1.6.2-py3-none-any.whl
Collecting pyinotify>=0.9.2 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/e3/c0/fd5b18dde17c1249658521f69598f3252f11d9d7a980c5be8619970646e1/pyinotify-0.9.6.tar.gz
Collecting python-dateutil>=1.4.1 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting raven>=5.1.1 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/bd/8e/62e26a88c0a1bbae677200baf0767c1022321a6555634f8129e6d55c5ddc/raven-6.10.0-py2.py3-none-any.whl
Collecting reportlab>=2.4 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/a5/d0/e3395ce0fab33245a6597a5db58e99b78e512ae9ae904aa2e7811e332f97/reportlab-3.5.21-cp36-cp36m-manylinux1_x86_64.whl
Collecting weasyprint>=0.15 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/e0/ea/89794c7b8e3298a06e5f5b7c0ad9eccf0d4ce0d3ac7626fd2762272550cd/WeasyPrint-47-py3-none-any.whl
Collecting xlwt>=0.7.2 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/44/48/def306413b25c3d01753603b1a222a011b8621aed27cd7f89cbc27e6b0f4/xlwt-1.3.0-py2.py3-none-any.whl
Collecting zope.interface>=3.0 (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/19/17/1d198a6aaa9aa4590862fe3d3a2ed7dd808050cab4eebe8a2f2f813c1376/zope.interface-4.6.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyopenssl>=0.16.0 (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl
Collecting pykcs11>=1.3.2 (from -r requirements.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/f6/a0/2800ff56c0b3856d1af410f8494836672339d7566d975a62bf81a4ad5716/PyKCS11-1.5.5.tar.gz
Collecting lxml>=3.3.3 (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/35/8a/5e066949f2b40caac32c7b2a77da63ad304b5fbe869036cc3fe4a198f724/lxml-4.3.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting cryptography>=1.4 (from -r requirements.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/5b/12/b0409a94dad366d98a8eee2a77678c7a73aafd8c0e4b835abea634ea3896/cryptography-2.6.1-cp34-abi3-manylinux1_x86_64.whl
Collecting python-nss>=0.12 (from -r requirements.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/6b/29/629098e34951c358b1f04f13a70b3590eb0cf2df817d945bd05c4169d71b/python-nss-1.0.1.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2_wy2d39/python-nss/setup.py", line 409, in <module>
        sys.exit(main(sys.argv))
      File "/tmp/pip-build-2_wy2d39/python-nss/setup.py", line 333, in main
        nss_include_dir  = find_include_dir(['nss3', 'nss'],   ['nss.h',  'pk11pub.h'], include_roots=include_roots)
      File "/tmp/pip-build-2_wy2d39/python-nss/setup.py", line 94, in find_include_dir
        raise ValueError("unable to locate include directory containing header files %s" % include_files)
    ValueError: unable to locate include directory containing header files ['nss.h', 'pk11pub.h']
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2_wy2d39/python-nss/

```
E ao tentar instalar as dependências com apt-get tambem da erro

```
renato@renato-Virtual-Machine:~/repos/stoq$ sudo apt-get install python python-gtk2 python-zopeinterface python-psycopg2 python-imaging      python-reportlab postgresql postgresql-client python-dateutil python-mako python-gudev      python-poppler python-webkit python-twisted-core python-twisted-web librsvg2-common python-xlwt      gettext intltool git git-review python-setuptools pep8 pyflakes python-mock pylint python-storm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python-zope.interface' instead of 'python-zopeinterface'
Package python-imaging is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-pil

Package python-webkit is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-imaging' has no installation candidate
E: Unable to locate package python-gudev
E: Package 'python-webkit' has no installation candidate

```

Estou usando essa versão do linux
```
renato@renato-Virtual-Machine:~/repos/stoq$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

Muito obrigado

**Comment by farribeiro** [comment]
Amigo aqui é apenas um espelho para a o repositório do projeto, que está em servidor próprio, e o fórum de suporte se encontra em servidor próprio. não me recordo os links de primeira mão... assim que tiver estarei postando aqui

**Comment by renato04** [comment]
@farribeiro Muito obrigado, vou tentar fazer o que vc indicou.
